import 'planning_models.dart';

/// ForgeFit's read-only, device-local movement catalogue.
///
/// IDs are persisted by templates and workout sessions, so existing IDs must
/// never be renamed. User-created movements remain separate private records.
abstract final class SystemExerciseCatalog {
  static final List<ExerciseSelection> all = List.unmodifiable(
    _seeds.map((seed) => seed.build()),
  );

  static final Map<String, ExerciseSelection> _byKey = Map.unmodifiable({
    for (final exercise in all) exercise.exerciseId: exercise,
  });

  static ExerciseSelection? byKey(String key) => _byKey[key];

  static List<ExerciseSelection> search({
    String query = '',
    MuscleGroup? muscleGroup,
    ExerciseEquipment? equipment,
  }) {
    final seen = <String>{};
    return List.unmodifiable(
      all.where(
        (exercise) =>
            seen.add(exercise.exerciseId) &&
            exercise.matchesSearch(query) &&
            (muscleGroup == null ||
                exercise.primaryMuscleGroup == muscleGroup ||
                exercise.secondaryMuscleGroups.contains(muscleGroup)) &&
            (equipment == null || exercise.equipment == equipment),
      ),
    );
  }

  static const List<_ExerciseSeed> _seeds = [
    // Chest
    _ExerciseSeed(
      'barbell_bench_press',
      'Barbell bench press',
      MuscleGroup.chest,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.triceps, MuscleGroup.shoulders],
      aliases: ['bench', 'flat bench', 'barbell bench'],
      keywords: ['horizontal press', 'pec press'],
    ),
    _ExerciseSeed(
      'incline_barbell_bench_press',
      'Incline Barbell Bench Press',
      MuscleGroup.chest,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
      aliases: ['incline bench'],
      keywords: ['upper chest', 'bench press'],
    ),
    _ExerciseSeed(
      'decline_barbell_bench_press',
      'Decline Barbell Bench Press',
      MuscleGroup.chest,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.triceps],
      aliases: ['decline bench'],
      keywords: ['lower chest', 'bench press'],
    ),
    _ExerciseSeed(
      'flat_dumbbell_bench_press',
      'Flat Dumbbell Bench Press',
      MuscleGroup.chest,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.triceps, MuscleGroup.shoulders],
      aliases: ['dumbbell bench', 'db bench'],
      keywords: ['horizontal press', 'pec press'],
    ),
    _ExerciseSeed(
      'incline_dumbbell_press',
      'Incline dumbbell press',
      MuscleGroup.chest,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
      aliases: ['incline dumbbell press', 'incline db bench'],
      keywords: ['upper chest', 'bench press'],
    ),
    _ExerciseSeed(
      'decline_dumbbell_bench_press',
      'Decline Dumbbell Bench Press',
      MuscleGroup.chest,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.triceps],
      aliases: ['decline db bench'],
      keywords: ['lower chest', 'bench press'],
    ),
    _ExerciseSeed(
      'machine_chest_press',
      'Machine chest press',
      MuscleGroup.chest,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.triceps, MuscleGroup.shoulders],
      aliases: ['machine bench', 'bench machine'],
      keywords: ['pec press', 'horizontal press'],
    ),
    _ExerciseSeed(
      'incline_machine_chest_press',
      'Incline Machine Chest Press',
      MuscleGroup.chest,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
      aliases: ['incline machine bench'],
      keywords: ['upper chest', 'bench press'],
    ),
    _ExerciseSeed(
      'plate_loaded_chest_press',
      'Plate-Loaded Chest Press',
      MuscleGroup.chest,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.triceps, MuscleGroup.shoulders],
      aliases: ['plate loaded bench', 'hammer strength chest press'],
      keywords: ['pec press', 'bench'],
    ),
    _ExerciseSeed(
      'plate_loaded_incline_chest_press',
      'Plate-Loaded Incline Chest Press',
      MuscleGroup.chest,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
      aliases: ['incline hammer press'],
      keywords: ['upper chest', 'bench'],
    ),
    _ExerciseSeed(
      'smith_machine_bench_press',
      'Smith Machine Bench Press',
      MuscleGroup.chest,
      ExerciseEquipment.smithMachine,
      secondary: [MuscleGroup.triceps, MuscleGroup.shoulders],
      aliases: ['smith bench'],
      keywords: ['horizontal press', 'pec press'],
    ),
    _ExerciseSeed(
      'smith_machine_incline_press',
      'Smith Machine Incline Press',
      MuscleGroup.chest,
      ExerciseEquipment.smithMachine,
      secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
      aliases: ['smith incline bench'],
      keywords: ['upper chest', 'bench press'],
    ),
    _ExerciseSeed(
      'pec_deck',
      'Pec Deck',
      MuscleGroup.chest,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['pec fly', 'machine fly'],
      keywords: ['chest fly', 'chest isolation'],
    ),
    _ExerciseSeed(
      'dumbbell_fly',
      'Dumbbell Fly',
      MuscleGroup.chest,
      ExerciseEquipment.dumbbell,
      aliases: ['db fly', 'pec fly'],
      keywords: ['chest fly', 'chest isolation'],
    ),
    _ExerciseSeed(
      'incline_dumbbell_fly',
      'Incline Dumbbell Fly',
      MuscleGroup.chest,
      ExerciseEquipment.dumbbell,
      aliases: ['incline pec fly'],
      keywords: ['upper chest', 'chest fly'],
    ),
    _ExerciseSeed(
      'cable_fly',
      'Cable fly',
      MuscleGroup.chest,
      ExerciseEquipment.cable,
      aliases: ['pec fly', 'cable crossover'],
      keywords: ['chest fly', 'chest isolation'],
    ),
    _ExerciseSeed(
      'low_to_high_cable_fly',
      'Low-to-High Cable Fly',
      MuscleGroup.chest,
      ExerciseEquipment.cable,
      aliases: ['low high cable fly', 'upper chest fly'],
      keywords: ['pec fly', 'cable crossover'],
    ),
    _ExerciseSeed(
      'high_to_low_cable_fly',
      'High-to-Low Cable Fly',
      MuscleGroup.chest,
      ExerciseEquipment.cable,
      aliases: ['high low cable fly', 'lower chest fly'],
      keywords: ['pec fly', 'cable crossover'],
    ),
    _ExerciseSeed(
      'single_arm_cable_fly',
      'Single-Arm Cable Fly',
      MuscleGroup.chest,
      ExerciseEquipment.cable,
      aliases: ['one arm pec fly'],
      keywords: ['unilateral chest', 'cable crossover'],
    ),
    _ExerciseSeed(
      'push_up',
      'Push-up',
      MuscleGroup.chest,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.triceps, MuscleGroup.shoulders, MuscleGroup.core],
      aliases: ['pushup', 'press up'],
      keywords: ['bodyweight chest', 'floor press'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'incline_push_up',
      'Incline Push-Up',
      MuscleGroup.chest,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.triceps],
      aliases: ['incline pushup'],
      keywords: ['elevated push up', 'bodyweight chest'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'decline_push_up',
      'Decline Push-Up',
      MuscleGroup.chest,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
      aliases: ['decline pushup'],
      keywords: ['feet elevated push up', 'upper chest'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'weighted_push_up',
      'Weighted Push-Up',
      MuscleGroup.chest,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.triceps, MuscleGroup.shoulders],
      aliases: ['loaded pushup'],
      keywords: ['weighted bodyweight chest', 'bench'],
      bodyweightRelevant: true,
    ),
    _ExerciseSeed(
      'chest_dip',
      'Chest Dip',
      MuscleGroup.chest,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.triceps, MuscleGroup.shoulders],
      aliases: ['forward lean dip'],
      keywords: ['bodyweight chest', 'parallel bar'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'assisted_chest_dip',
      'Assisted Chest Dip',
      MuscleGroup.chest,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.triceps],
      aliases: ['assisted dip'],
      keywords: ['machine dip', 'bodyweight chest'],
      bodyweightRelevant: true,
    ),

    // Back
    _ExerciseSeed(
      'lat_pulldown',
      'Lat pulldown',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.biceps],
      aliases: ['lat pulldown', 'wide pulldown'],
      keywords: ['lats', 'vertical pull'],
    ),
    _ExerciseSeed(
      'neutral_grip_lat_pulldown',
      'Neutral-Grip Lat Pulldown',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.biceps],
      aliases: ['neutral pulldown'],
      keywords: ['lats', 'vertical pull'],
    ),
    _ExerciseSeed(
      'close_grip_lat_pulldown',
      'Close-Grip Lat Pulldown',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.biceps],
      aliases: ['close pulldown'],
      keywords: ['lats', 'vertical pull'],
    ),
    _ExerciseSeed(
      'underhand_lat_pulldown',
      'Underhand Lat Pulldown',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.biceps],
      aliases: ['reverse grip pulldown'],
      keywords: ['lats', 'vertical pull'],
    ),
    _ExerciseSeed(
      'single_arm_lat_pulldown',
      'Single-Arm Lat Pulldown',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.biceps],
      aliases: ['one arm pulldown'],
      keywords: ['unilateral lats', 'vertical pull'],
    ),
    _ExerciseSeed(
      'kneeling_single_arm_pulldown',
      'Kneeling Single-Arm Pulldown',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.biceps, MuscleGroup.core],
      aliases: ['kneeling lat pulldown'],
      keywords: ['unilateral lats', 'vertical pull'],
    ),
    _ExerciseSeed(
      'pull_up',
      'Pull-up',
      MuscleGroup.back,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.biceps, MuscleGroup.core],
      aliases: ['pullup'],
      keywords: ['lats', 'vertical pull'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'assisted_pull_up',
      'Assisted Pull-Up',
      MuscleGroup.back,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.biceps],
      aliases: ['assisted pullup'],
      keywords: ['lats', 'vertical pull'],
      bodyweightRelevant: true,
    ),
    _ExerciseSeed(
      'weighted_pull_up',
      'Weighted Pull-Up',
      MuscleGroup.back,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.biceps, MuscleGroup.core],
      aliases: ['weighted pullup'],
      keywords: ['lats', 'vertical pull'],
      bodyweightRelevant: true,
    ),
    _ExerciseSeed(
      'chin_up',
      'Chin-Up',
      MuscleGroup.back,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.biceps],
      aliases: ['chinup', 'underhand pull up'],
      keywords: ['lats', 'vertical pull'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'assisted_chin_up',
      'Assisted Chin-Up',
      MuscleGroup.back,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.biceps],
      aliases: ['assisted chinup'],
      keywords: ['lats', 'vertical pull'],
      bodyweightRelevant: true,
    ),
    _ExerciseSeed(
      'seated_cable_row',
      'Seated Cable Row',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.biceps],
      aliases: ['cable row'],
      keywords: ['upper back row', 'lat row', 'horizontal pull'],
    ),
    _ExerciseSeed(
      'wide_grip_cable_row',
      'Wide-Grip Cable Row',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.shoulders, MuscleGroup.biceps],
      aliases: ['wide cable row'],
      keywords: ['upper back row', 'rear delt row'],
    ),
    _ExerciseSeed(
      'close_grip_cable_row',
      'Close-Grip Cable Row',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.biceps],
      aliases: ['close cable row'],
      keywords: ['lat row', 'horizontal pull'],
    ),
    _ExerciseSeed(
      'single_arm_cable_row',
      'Single-Arm Cable Row',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.biceps],
      aliases: ['one arm cable row'],
      keywords: ['lat row', 'unilateral back'],
    ),
    _ExerciseSeed(
      'chest_supported_dumbbell_row',
      'Chest-Supported Dumbbell Row',
      MuscleGroup.back,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.biceps, MuscleGroup.shoulders],
      aliases: ['chest supported row'],
      keywords: ['upper back row', 'lat row'],
    ),
    _ExerciseSeed(
      'dumbbell_row',
      'One-Arm Dumbbell Row',
      MuscleGroup.back,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.biceps],
      aliases: ['dumbbell row', 'db row'],
      keywords: ['lat row', 'unilateral back'],
    ),
    _ExerciseSeed(
      'barbell_row',
      'Barbell row',
      MuscleGroup.back,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.biceps, MuscleGroup.hamstrings],
      aliases: ['bent over row'],
      keywords: ['upper back row', 'lat row', 'horizontal pull'],
    ),
    _ExerciseSeed(
      'pendlay_row',
      'Pendlay Row',
      MuscleGroup.back,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.biceps, MuscleGroup.hamstrings],
      aliases: ['dead stop barbell row'],
      keywords: ['upper back row', 'horizontal pull'],
    ),
    _ExerciseSeed(
      't_bar_row',
      'T-Bar Row',
      MuscleGroup.back,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.biceps],
      aliases: ['tbar row'],
      keywords: ['upper back row', 'lat row'],
    ),
    _ExerciseSeed(
      'landmine_row',
      'Landmine Row',
      MuscleGroup.back,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.biceps],
      aliases: ['landmine t bar row'],
      keywords: ['upper back row', 'horizontal pull'],
    ),
    _ExerciseSeed(
      'seated_machine_row',
      'Seated machine row',
      MuscleGroup.back,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.biceps],
      aliases: ['machine row'],
      keywords: ['upper back row', 'lat row'],
    ),
    _ExerciseSeed(
      'plate_loaded_row',
      'Plate-Loaded Row',
      MuscleGroup.back,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.biceps],
      aliases: ['hammer strength row'],
      keywords: ['upper back row', 'lat row'],
    ),
    _ExerciseSeed(
      'plate_loaded_high_row',
      'Plate-Loaded High Row',
      MuscleGroup.back,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.biceps, MuscleGroup.shoulders],
      aliases: ['high row'],
      keywords: ['upper back row', 'lat row'],
    ),
    _ExerciseSeed(
      'single_arm_machine_row',
      'Single-Arm Machine Row',
      MuscleGroup.back,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.biceps],
      aliases: ['one arm machine row'],
      keywords: ['unilateral lat row', 'upper back row'],
    ),
    _ExerciseSeed(
      'straight_arm_pulldown',
      'Straight-Arm Pulldown',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.triceps],
      aliases: ['straight arm lat pulldown'],
      keywords: ['lats', 'cable pullover'],
    ),
    _ExerciseSeed(
      'dumbbell_pullover',
      'Dumbbell Pullover',
      MuscleGroup.back,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.chest, MuscleGroup.triceps],
      aliases: ['db pullover'],
      keywords: ['lats', 'shoulder extension'],
    ),
    _ExerciseSeed(
      'cable_pullover',
      'Cable Pullover',
      MuscleGroup.back,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.triceps],
      aliases: ['cable lat pullover'],
      keywords: ['lats', 'straight arm pulldown'],
    ),
    _ExerciseSeed(
      'machine_pullover',
      'Machine Pullover',
      MuscleGroup.back,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.triceps],
      aliases: ['nautilus pullover'],
      keywords: ['lats', 'shoulder extension'],
    ),
    _ExerciseSeed(
      'back_extension',
      'Back Extension',
      MuscleGroup.back,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
      aliases: ['hyperextension'],
      keywords: ['lower back', 'erectors'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'band_pull_apart',
      'Band pull-apart',
      MuscleGroup.back,
      ExerciseEquipment.resistanceBand,
      secondary: [MuscleGroup.shoulders],
      aliases: ['band pull apart'],
      keywords: ['upper back', 'rear delt', 'posture'],
    ),

    // Shoulders
    _ExerciseSeed(
      'barbell_overhead_press',
      'Barbell overhead press',
      MuscleGroup.shoulders,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.triceps, MuscleGroup.core],
      aliases: ['ohp', 'military press'],
      keywords: ['shoulder press', 'vertical press'],
    ),
    _ExerciseSeed(
      'seated_barbell_shoulder_press',
      'Seated Barbell Shoulder Press',
      MuscleGroup.shoulders,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.triceps],
      aliases: ['seated ohp'],
      keywords: ['overhead press', 'vertical press'],
    ),
    _ExerciseSeed(
      'dumbbell_shoulder_press',
      'Dumbbell Shoulder Press',
      MuscleGroup.shoulders,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.triceps],
      aliases: ['dumbbell ohp', 'db shoulder press'],
      keywords: ['overhead press', 'vertical press'],
    ),
    _ExerciseSeed(
      'single_arm_dumbbell_shoulder_press',
      'Single-Arm Dumbbell Shoulder Press',
      MuscleGroup.shoulders,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.triceps, MuscleGroup.core],
      aliases: ['one arm dumbbell ohp'],
      keywords: ['unilateral overhead press'],
    ),
    _ExerciseSeed(
      'arnold_press',
      'Arnold Press',
      MuscleGroup.shoulders,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.triceps],
      aliases: ['arnold shoulder press'],
      keywords: ['overhead press', 'front delt'],
    ),
    _ExerciseSeed(
      'machine_shoulder_press',
      'Machine Shoulder Press',
      MuscleGroup.shoulders,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.triceps],
      aliases: ['machine ohp'],
      keywords: ['overhead press', 'vertical press'],
    ),
    _ExerciseSeed(
      'plate_loaded_shoulder_press',
      'Plate-Loaded Shoulder Press',
      MuscleGroup.shoulders,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.triceps],
      aliases: ['plate loaded ohp'],
      keywords: ['overhead press', 'vertical press'],
    ),
    _ExerciseSeed(
      'smith_shoulder_press',
      'Smith machine shoulder press',
      MuscleGroup.shoulders,
      ExerciseEquipment.smithMachine,
      secondary: [MuscleGroup.triceps],
      aliases: ['smith ohp'],
      keywords: ['overhead press', 'vertical press'],
    ),
    _ExerciseSeed(
      'landmine_press',
      'Landmine Press',
      MuscleGroup.shoulders,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.chest, MuscleGroup.triceps],
      aliases: ['angled barbell press'],
      keywords: ['shoulder press', 'scapular plane'],
    ),
    _ExerciseSeed(
      'dumbbell_lateral_raise',
      'Dumbbell lateral raise',
      MuscleGroup.shoulders,
      ExerciseEquipment.dumbbell,
      aliases: ['side raise', 'side delt raise'],
      keywords: ['side delt', 'medial delt'],
    ),
    _ExerciseSeed(
      'cable_lateral_raise',
      'Cable Lateral Raise',
      MuscleGroup.shoulders,
      ExerciseEquipment.cable,
      aliases: ['cable side raise'],
      keywords: ['side delt', 'medial delt'],
    ),
    _ExerciseSeed(
      'single_arm_cable_lateral_raise',
      'Single-Arm Cable Lateral Raise',
      MuscleGroup.shoulders,
      ExerciseEquipment.cable,
      aliases: ['one arm cable side raise'],
      keywords: ['side delt', 'medial delt'],
    ),
    _ExerciseSeed(
      'leaning_cable_lateral_raise',
      'Leaning Cable Lateral Raise',
      MuscleGroup.shoulders,
      ExerciseEquipment.cable,
      aliases: ['lean away lateral raise'],
      keywords: ['side delt', 'medial delt'],
    ),
    _ExerciseSeed(
      'machine_lateral_raise',
      'Machine Lateral Raise',
      MuscleGroup.shoulders,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['machine side raise'],
      keywords: ['side delt', 'medial delt'],
    ),
    _ExerciseSeed(
      'dumbbell_front_raise',
      'Dumbbell Front Raise',
      MuscleGroup.shoulders,
      ExerciseEquipment.dumbbell,
      aliases: ['db front raise'],
      keywords: ['front delt', 'anterior delt'],
    ),
    _ExerciseSeed(
      'cable_front_raise',
      'Cable Front Raise',
      MuscleGroup.shoulders,
      ExerciseEquipment.cable,
      aliases: ['cable anterior raise'],
      keywords: ['front delt', 'anterior delt'],
    ),
    _ExerciseSeed(
      'plate_front_raise',
      'Plate Front Raise',
      MuscleGroup.shoulders,
      ExerciseEquipment.other,
      aliases: ['weight plate raise'],
      keywords: ['front delt', 'anterior delt'],
    ),
    _ExerciseSeed(
      'rear_delt_dumbbell_fly',
      'Rear-Delt Dumbbell Fly',
      MuscleGroup.shoulders,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.back],
      aliases: ['rear delt fly', 'bent over reverse fly'],
      keywords: ['posterior delt', 'upper back'],
    ),
    _ExerciseSeed(
      'reverse_pec_deck',
      'Reverse Pec Deck',
      MuscleGroup.shoulders,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.back],
      aliases: ['rear delt machine', 'reverse fly'],
      keywords: ['rear delt', 'posterior delt'],
    ),
    _ExerciseSeed(
      'cable_rear_delt_fly',
      'Cable Rear-Delt Fly',
      MuscleGroup.shoulders,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.back],
      aliases: ['rear delt cable fly', 'cable reverse fly'],
      keywords: ['rear delt', 'posterior delt'],
    ),
    _ExerciseSeed(
      'cable_face_pull',
      'Cable face pull',
      MuscleGroup.shoulders,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.back],
      aliases: ['face pull'],
      keywords: ['rear delt', 'rotator cuff', 'upper back'],
    ),
    _ExerciseSeed(
      'barbell_upright_row',
      'Barbell Upright Row',
      MuscleGroup.shoulders,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.back, MuscleGroup.biceps],
      aliases: ['upright row'],
      keywords: ['side delt', 'upper traps'],
    ),
    _ExerciseSeed(
      'cable_upright_row',
      'Cable Upright Row',
      MuscleGroup.shoulders,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.back, MuscleGroup.biceps],
      aliases: ['rope upright row'],
      keywords: ['side delt', 'upper traps'],
    ),
    _ExerciseSeed(
      'incline_dumbbell_y_raise',
      'Incline Dumbbell Y-Raise',
      MuscleGroup.shoulders,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.back],
      aliases: ['y raise'],
      keywords: ['lower traps', 'rear delt', 'scapular'],
    ),
    _ExerciseSeed(
      'cable_y_raise',
      'Cable Y-Raise',
      MuscleGroup.shoulders,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.back],
      aliases: ['cable y raise'],
      keywords: ['lower traps', 'rear delt', 'scapular'],
    ),
    _ExerciseSeed(
      'band_lateral_raise',
      'Resistance-Band Lateral Raise',
      MuscleGroup.shoulders,
      ExerciseEquipment.resistanceBand,
      aliases: ['band side raise'],
      keywords: ['side delt', 'medial delt'],
    ),

    // Biceps
    _ExerciseSeed(
      'barbell_curl',
      'Barbell curl',
      MuscleGroup.biceps,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.forearms],
      aliases: ['straight bar curl'],
      keywords: ['arm curl', 'bicep curl'],
    ),
    _ExerciseSeed(
      'ez_bar_curl',
      'EZ-Bar Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.forearms],
      aliases: ['ez curl'],
      keywords: ['arm curl', 'bicep curl'],
    ),
    _ExerciseSeed(
      'dumbbell_curl',
      'Dumbbell Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.forearms],
      aliases: ['db curl'],
      keywords: ['arm curl', 'bicep curl'],
    ),
    _ExerciseSeed(
      'alternating_dumbbell_curl',
      'Alternating Dumbbell Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.forearms],
      aliases: ['alternating db curl'],
      keywords: ['arm curl', 'bicep curl'],
    ),
    _ExerciseSeed(
      'hammer_curl',
      'Hammer Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.forearms],
      aliases: ['neutral grip curl'],
      keywords: ['brachialis', 'forearm curl'],
    ),
    _ExerciseSeed(
      'cross_body_hammer_curl',
      'Cross-Body Hammer Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.forearms],
      aliases: ['crossbody curl'],
      keywords: ['brachialis', 'neutral grip curl'],
    ),
    _ExerciseSeed(
      'incline_dumbbell_curl',
      'Incline dumbbell curl',
      MuscleGroup.biceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.forearms],
      aliases: ['incline db curl'],
      keywords: ['long head bicep', 'stretch curl'],
    ),
    _ExerciseSeed(
      'bayesian_cable_curl',
      'Bayesian Cable Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.cable,
      aliases: ['behind body cable curl'],
      keywords: ['long head bicep', 'stretch curl'],
    ),
    _ExerciseSeed(
      'preacher_curl',
      'Barbell Preacher Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.forearms],
      aliases: ['preacher curl'],
      keywords: ['supported arm curl', 'bicep curl'],
    ),
    _ExerciseSeed(
      'ez_bar_preacher_curl',
      'EZ-Bar Preacher Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.barbell,
      aliases: ['ez preacher curl'],
      keywords: ['supported arm curl', 'bicep curl'],
    ),
    _ExerciseSeed(
      'dumbbell_preacher_curl',
      'Dumbbell Preacher Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.dumbbell,
      aliases: ['db preacher curl'],
      keywords: ['supported arm curl', 'bicep curl'],
    ),
    _ExerciseSeed(
      'machine_preacher_curl',
      'Machine Preacher Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['preacher curl machine'],
      keywords: ['supported arm curl', 'bicep curl'],
    ),
    _ExerciseSeed(
      'machine_biceps_curl',
      'Machine Biceps Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['machine curl'],
      keywords: ['arm curl', 'bicep curl'],
    ),
    _ExerciseSeed(
      'spider_curl',
      'Spider Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.dumbbell,
      aliases: ['chest supported curl'],
      keywords: ['short head bicep', 'arm curl'],
    ),
    _ExerciseSeed(
      'concentration_curl',
      'Concentration Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.dumbbell,
      aliases: ['seated single arm curl'],
      keywords: ['bicep isolation', 'arm curl'],
    ),
    _ExerciseSeed(
      'cable_curl',
      'Cable curl',
      MuscleGroup.biceps,
      ExerciseEquipment.cable,
      aliases: ['cable bicep curl'],
      keywords: ['arm curl', 'constant tension'],
    ),
    _ExerciseSeed(
      'straight_bar_cable_curl',
      'Straight-Bar Cable Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.cable,
      aliases: ['bar cable curl'],
      keywords: ['arm curl', 'bicep curl'],
    ),
    _ExerciseSeed(
      'rope_cable_curl',
      'Rope Cable Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.forearms],
      aliases: ['rope hammer curl'],
      keywords: ['neutral grip curl', 'brachialis'],
    ),
    _ExerciseSeed(
      'single_arm_cable_curl',
      'Single-Arm Cable Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.cable,
      aliases: ['one arm cable curl'],
      keywords: ['unilateral bicep', 'arm curl'],
    ),
    _ExerciseSeed(
      'zottman_curl',
      'Zottman Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.forearms],
      aliases: ['pronated eccentric curl'],
      keywords: ['bicep forearm curl'],
    ),
    _ExerciseSeed(
      'drag_curl',
      'Barbell Drag Curl',
      MuscleGroup.biceps,
      ExerciseEquipment.barbell,
      aliases: ['drag curl'],
      keywords: ['long head bicep', 'arm curl'],
    ),

    // Triceps
    _ExerciseSeed(
      'rope_pushdown',
      'Rope pushdown',
      MuscleGroup.triceps,
      ExerciseEquipment.cable,
      aliases: ['rope pushdown', 'tricep pushdown'],
      keywords: ['cable extension', 'arm isolation'],
    ),
    _ExerciseSeed(
      'straight_bar_pushdown',
      'Straight-Bar Triceps Pushdown',
      MuscleGroup.triceps,
      ExerciseEquipment.cable,
      aliases: ['bar pushdown', 'tricep pushdown'],
      keywords: ['cable extension', 'arm isolation'],
    ),
    _ExerciseSeed(
      'v_bar_pushdown',
      'V-Bar Triceps Pushdown',
      MuscleGroup.triceps,
      ExerciseEquipment.cable,
      aliases: ['v bar pushdown', 'tricep pushdown'],
      keywords: ['cable extension', 'arm isolation'],
    ),
    _ExerciseSeed(
      'single_arm_pushdown',
      'Single-Arm Triceps Pushdown',
      MuscleGroup.triceps,
      ExerciseEquipment.cable,
      aliases: ['one arm pushdown', 'tricep pushdown'],
      keywords: ['unilateral cable extension'],
    ),
    _ExerciseSeed(
      'reverse_grip_pushdown',
      'Reverse-Grip Triceps Pushdown',
      MuscleGroup.triceps,
      ExerciseEquipment.cable,
      aliases: ['underhand pushdown', 'tricep pushdown'],
      keywords: ['cable extension', 'medial head'],
    ),
    _ExerciseSeed(
      'overhead_rope_extension',
      'Overhead Rope Triceps Extension',
      MuscleGroup.triceps,
      ExerciseEquipment.cable,
      aliases: ['rope overhead extension'],
      keywords: ['long head tricep', 'cable extension'],
    ),
    _ExerciseSeed(
      'single_arm_overhead_cable_extension',
      'Single-Arm Overhead Cable Extension',
      MuscleGroup.triceps,
      ExerciseEquipment.cable,
      aliases: ['one arm overhead tricep extension'],
      keywords: ['long head tricep', 'unilateral extension'],
    ),
    _ExerciseSeed(
      'dumbbell_overhead_extension',
      'Dumbbell Overhead Triceps Extension',
      MuscleGroup.triceps,
      ExerciseEquipment.dumbbell,
      aliases: ['db overhead extension'],
      keywords: ['long head tricep', 'arm extension'],
    ),
    _ExerciseSeed(
      'barbell_skull_crusher',
      'Barbell Skull Crusher',
      MuscleGroup.triceps,
      ExerciseEquipment.barbell,
      aliases: ['lying tricep extension'],
      keywords: ['elbow extension', 'arm isolation'],
    ),
    _ExerciseSeed(
      'ez_bar_skull_crusher',
      'EZ-Bar Skull Crusher',
      MuscleGroup.triceps,
      ExerciseEquipment.barbell,
      aliases: ['ez lying tricep extension'],
      keywords: ['elbow extension', 'arm isolation'],
    ),
    _ExerciseSeed(
      'dumbbell_skull_crusher',
      'Dumbbell Skull Crusher',
      MuscleGroup.triceps,
      ExerciseEquipment.dumbbell,
      aliases: ['db lying tricep extension'],
      keywords: ['elbow extension', 'arm isolation'],
    ),
    _ExerciseSeed(
      'close_grip_bench_press',
      'Close-grip bench press',
      MuscleGroup.triceps,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.chest, MuscleGroup.shoulders],
      aliases: ['close grip bench', 'cgbp'],
      keywords: ['tricep press', 'bench'],
    ),
    _ExerciseSeed(
      'assisted_triceps_dip',
      'Assisted Triceps Dip',
      MuscleGroup.triceps,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.chest],
      aliases: ['assisted dip'],
      keywords: ['machine dip', 'bodyweight tricep'],
      bodyweightRelevant: true,
    ),
    _ExerciseSeed(
      'machine_triceps_dip',
      'Machine Triceps Dip',
      MuscleGroup.triceps,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.chest],
      aliases: ['seated dip machine'],
      keywords: ['tricep press', 'dip'],
    ),
    _ExerciseSeed(
      'bench_dip',
      'Bench dip',
      MuscleGroup.triceps,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.chest, MuscleGroup.shoulders],
      aliases: ['chair dip'],
      keywords: ['bodyweight tricep', 'dip'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'dumbbell_triceps_kickback',
      'Dumbbell Triceps Kickback',
      MuscleGroup.triceps,
      ExerciseEquipment.dumbbell,
      aliases: ['db kickback'],
      keywords: ['tricep extension', 'arm isolation'],
    ),
    _ExerciseSeed(
      'cable_triceps_kickback',
      'Cable Triceps Kickback',
      MuscleGroup.triceps,
      ExerciseEquipment.cable,
      aliases: ['tricep cable kickback'],
      keywords: ['tricep extension', 'arm isolation'],
    ),
    _ExerciseSeed(
      'jm_press',
      'JM Press',
      MuscleGroup.triceps,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.chest],
      aliases: ['jm bench press'],
      keywords: ['tricep press', 'elbow extension'],
    ),
    _ExerciseSeed(
      'band_triceps_pushdown',
      'Resistance-Band Triceps Pushdown',
      MuscleGroup.triceps,
      ExerciseEquipment.resistanceBand,
      aliases: ['band pushdown', 'tricep pushdown'],
      keywords: ['arm extension', 'home workout'],
    ),

    // Forearms
    _ExerciseSeed(
      'wrist_curl',
      'Dumbbell wrist curl',
      MuscleGroup.forearms,
      ExerciseEquipment.dumbbell,
      aliases: ['wrist curl'],
      keywords: ['forearm flexion', 'grip'],
    ),
    _ExerciseSeed(
      'barbell_wrist_curl',
      'Barbell Wrist Curl',
      MuscleGroup.forearms,
      ExerciseEquipment.barbell,
      aliases: ['wrist flexion curl'],
      keywords: ['forearm flexion', 'grip'],
    ),
    _ExerciseSeed(
      'reverse_dumbbell_wrist_curl',
      'Reverse Dumbbell Wrist Curl',
      MuscleGroup.forearms,
      ExerciseEquipment.dumbbell,
      aliases: ['wrist extension curl'],
      keywords: ['forearm extensor', 'grip'],
    ),
    _ExerciseSeed(
      'behind_back_wrist_curl',
      'Behind-the-Back Wrist Curl',
      MuscleGroup.forearms,
      ExerciseEquipment.barbell,
      aliases: ['behind back forearm curl'],
      keywords: ['forearm flexion', 'grip'],
    ),
    _ExerciseSeed(
      'barbell_reverse_curl',
      'Barbell Reverse Curl',
      MuscleGroup.forearms,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.biceps],
      aliases: ['reverse curl'],
      keywords: ['brachioradialis', 'pronated curl'],
    ),
    _ExerciseSeed(
      'reverse_cable_curl',
      'Reverse cable curl',
      MuscleGroup.forearms,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.biceps],
      aliases: ['cable reverse curl'],
      keywords: ['brachioradialis', 'pronated curl'],
    ),
    _ExerciseSeed(
      'plate_pinch',
      'Plate Pinch',
      MuscleGroup.forearms,
      ExerciseEquipment.other,
      aliases: ['plate pinch hold'],
      keywords: ['grip strength', 'thumb grip'],
      trackingType: ExerciseTrackingType.weightAndDuration,
    ),
    _ExerciseSeed(
      'wrist_roller',
      'Wrist Roller',
      MuscleGroup.forearms,
      ExerciseEquipment.other,
      aliases: ['forearm roller'],
      keywords: ['grip endurance', 'wrist flexion extension'],
      trackingType: ExerciseTrackingType.weightAndRepetitions,
    ),
    _ExerciseSeed(
      'dead_hang',
      'Dead Hang',
      MuscleGroup.forearms,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.back, MuscleGroup.shoulders],
      aliases: ['bar hang'],
      keywords: ['grip endurance', 'shoulder decompression'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'towel_dead_hang',
      'Towel Dead Hang',
      MuscleGroup.forearms,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.back],
      aliases: ['towel hang'],
      keywords: ['grip endurance', 'crush grip'],
      trackingType: ExerciseTrackingType.duration,
    ),

    // Quadriceps
    _ExerciseSeed(
      'back_squat',
      'Barbell back squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.core],
      aliases: ['back squat', 'squat'],
      keywords: ['knee dominant', 'leg strength'],
    ),
    _ExerciseSeed(
      'front_squat',
      'Barbell Front Squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.core],
      aliases: ['front squat'],
      keywords: ['knee dominant', 'leg strength'],
    ),
    _ExerciseSeed(
      'high_bar_squat',
      'High-Bar Back Squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.core],
      aliases: ['high bar squat'],
      keywords: ['knee dominant', 'leg strength'],
    ),
    _ExerciseSeed(
      'low_bar_squat',
      'Low-Bar Back Squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
      aliases: ['low bar squat'],
      keywords: ['powerlifting squat', 'leg strength'],
    ),
    _ExerciseSeed(
      'goblet_squat',
      'Goblet Squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.core],
      aliases: ['dumbbell goblet squat'],
      keywords: ['knee dominant', 'leg strength'],
    ),
    _ExerciseSeed(
      'hack_squat',
      'Hack Squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.glutes],
      aliases: ['hack squat machine'],
      keywords: ['knee dominant', 'leg press'],
    ),
    _ExerciseSeed(
      'pendulum_squat',
      'Pendulum Squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.glutes],
      aliases: ['pendulum squat machine'],
      keywords: ['knee dominant', 'leg press'],
    ),
    _ExerciseSeed(
      'smith_machine_squat',
      'Smith Machine Squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.smithMachine,
      secondary: [MuscleGroup.glutes],
      aliases: ['smith squat'],
      keywords: ['knee dominant', 'leg strength'],
    ),
    _ExerciseSeed(
      'leg_press',
      'Leg press',
      MuscleGroup.quadriceps,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
      aliases: ['leg press'],
      keywords: ['sled press', 'knee dominant'],
    ),
    _ExerciseSeed(
      'horizontal_leg_press',
      'Horizontal Leg Press',
      MuscleGroup.quadriceps,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.glutes],
      aliases: ['seated leg press'],
      keywords: ['knee dominant', 'machine squat'],
    ),
    _ExerciseSeed(
      'single_leg_press',
      'Single-Leg Press',
      MuscleGroup.quadriceps,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.glutes],
      aliases: ['one leg press'],
      keywords: ['unilateral legs', 'knee dominant'],
    ),
    _ExerciseSeed(
      'bulgarian_split_squat',
      'Bulgarian Split Squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
      aliases: ['rear foot elevated split squat', 'bss'],
      keywords: ['unilateral legs', 'lunge'],
    ),
    _ExerciseSeed(
      'reverse_lunge',
      'Dumbbell Reverse Lunge',
      MuscleGroup.quadriceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
      aliases: ['reverse lunge'],
      keywords: ['unilateral legs', 'split squat'],
    ),
    _ExerciseSeed(
      'walking_lunge',
      'Dumbbell Walking Lunge',
      MuscleGroup.quadriceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
      aliases: ['walking lunge'],
      keywords: ['unilateral legs', 'split squat'],
    ),
    _ExerciseSeed(
      'forward_lunge',
      'Dumbbell Forward Lunge',
      MuscleGroup.quadriceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
      aliases: ['forward lunge'],
      keywords: ['unilateral legs', 'split squat'],
    ),
    _ExerciseSeed(
      'smith_split_squat',
      'Smith machine split squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.smithMachine,
      secondary: [MuscleGroup.glutes],
      aliases: ['smith split squat', 'smith lunge'],
      keywords: ['unilateral legs', 'knee dominant'],
    ),
    _ExerciseSeed(
      'dumbbell_step_up',
      'Dumbbell Step-Up',
      MuscleGroup.quadriceps,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings],
      aliases: ['step up'],
      keywords: ['unilateral legs', 'box step'],
    ),
    _ExerciseSeed(
      'leg_extension',
      'Leg Extension',
      MuscleGroup.quadriceps,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['knee extension'],
      keywords: ['quad isolation', 'machine legs'],
    ),
    _ExerciseSeed(
      'single_leg_extension',
      'Single-Leg Extension',
      MuscleGroup.quadriceps,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['one leg extension'],
      keywords: ['unilateral quad', 'knee extension'],
    ),
    _ExerciseSeed(
      'sissy_squat',
      'Sissy Squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.bodyweight,
      aliases: ['bodyweight sissy squat'],
      keywords: ['quad isolation', 'knee flexion'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'banded_spanish_squat',
      'Banded Spanish squat',
      MuscleGroup.quadriceps,
      ExerciseEquipment.resistanceBand,
      aliases: ['spanish squat'],
      keywords: ['quad isometric', 'knee friendly squat'],
    ),

    // Hamstrings
    _ExerciseSeed(
      'seated_leg_curl',
      'Seated leg curl',
      MuscleGroup.hamstrings,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['seated ham curl'],
      keywords: ['ham curl', 'knee flexion'],
    ),
    _ExerciseSeed(
      'lying_leg_curl',
      'Lying Leg Curl',
      MuscleGroup.hamstrings,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['lying ham curl', 'prone leg curl'],
      keywords: ['ham curl', 'knee flexion'],
    ),
    _ExerciseSeed(
      'standing_leg_curl',
      'Standing Leg Curl',
      MuscleGroup.hamstrings,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['standing ham curl'],
      keywords: ['ham curl', 'knee flexion'],
    ),
    _ExerciseSeed(
      'single_leg_curl',
      'Single-Leg Curl',
      MuscleGroup.hamstrings,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['one leg ham curl'],
      keywords: ['ham curl', 'unilateral hamstring'],
    ),
    _ExerciseSeed(
      'nordic_hamstring_curl',
      'Nordic Hamstring Curl',
      MuscleGroup.hamstrings,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.glutes],
      aliases: ['nordic curl', 'nordic ham curl'],
      keywords: ['eccentric hamstring', 'knee flexion'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'romanian_deadlift',
      'Romanian deadlift',
      MuscleGroup.hamstrings,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.back],
      aliases: ['romanian deadlift', 'rdl'],
      keywords: ['hip hinge', 'hamstring deadlift'],
    ),
    _ExerciseSeed(
      'dumbbell_romanian_deadlift',
      'Dumbbell Romanian Deadlift',
      MuscleGroup.hamstrings,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.back],
      aliases: ['dumbbell rdl', 'db rdl'],
      keywords: ['hip hinge', 'hamstring deadlift'],
    ),
    _ExerciseSeed(
      'dumbbell_single_leg_rdl',
      'Dumbbell single-leg RDL',
      MuscleGroup.hamstrings,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.core],
      aliases: ['single leg rdl', 'one leg rdl'],
      keywords: ['unilateral hip hinge', 'hamstring deadlift'],
    ),
    _ExerciseSeed(
      'stiff_leg_deadlift',
      'Stiff-Leg Deadlift',
      MuscleGroup.hamstrings,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.back],
      aliases: ['stiff legged deadlift'],
      keywords: ['hip hinge', 'hamstring deadlift'],
    ),
    _ExerciseSeed(
      'barbell_good_morning',
      'Barbell Good Morning',
      MuscleGroup.hamstrings,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.back],
      aliases: ['good morning'],
      keywords: ['hip hinge', 'posterior chain'],
    ),
    _ExerciseSeed(
      'cable_pull_through_hamstring',
      'Cable Hamstring Pull-Through',
      MuscleGroup.hamstrings,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.glutes],
      aliases: ['cable pull through'],
      keywords: ['hip hinge', 'posterior chain'],
    ),
    _ExerciseSeed(
      'stability_ball_leg_curl',
      'Stability-Ball Leg Curl',
      MuscleGroup.hamstrings,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.glutes, MuscleGroup.core],
      aliases: ['swiss ball ham curl'],
      keywords: ['ham curl', 'knee flexion'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'slider_leg_curl',
      'Slider Leg Curl',
      MuscleGroup.hamstrings,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.glutes, MuscleGroup.core],
      aliases: ['floor slider ham curl'],
      keywords: ['ham curl', 'knee flexion'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'banded_leg_curl',
      'Resistance-Band Leg Curl',
      MuscleGroup.hamstrings,
      ExerciseEquipment.resistanceBand,
      aliases: ['band ham curl'],
      keywords: ['ham curl', 'home workout'],
    ),

    // Glutes
    _ExerciseSeed(
      'barbell_hip_thrust',
      'Barbell hip thrust',
      MuscleGroup.glutes,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.hamstrings],
      aliases: ['hip thrust'],
      keywords: ['glute bridge', 'hip extension'],
    ),
    _ExerciseSeed(
      'smith_machine_hip_thrust',
      'Smith Machine Hip Thrust',
      MuscleGroup.glutes,
      ExerciseEquipment.smithMachine,
      secondary: [MuscleGroup.hamstrings],
      aliases: ['smith hip thrust'],
      keywords: ['glute bridge', 'hip extension'],
    ),
    _ExerciseSeed(
      'machine_hip_thrust',
      'Machine Hip Thrust',
      MuscleGroup.glutes,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.hamstrings],
      aliases: ['glute drive machine'],
      keywords: ['glute bridge', 'hip extension'],
    ),
    _ExerciseSeed(
      'dumbbell_hip_thrust',
      'Dumbbell Hip Thrust',
      MuscleGroup.glutes,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.hamstrings],
      aliases: ['db hip thrust'],
      keywords: ['glute bridge', 'hip extension'],
    ),
    _ExerciseSeed(
      'bodyweight_glute_bridge',
      'Bodyweight Glute Bridge',
      MuscleGroup.glutes,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.hamstrings],
      aliases: ['glute bridge'],
      keywords: ['floor hip extension', 'bodyweight glutes'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'banded_glute_bridge',
      'Banded glute bridge',
      MuscleGroup.glutes,
      ExerciseEquipment.resistanceBand,
      secondary: [MuscleGroup.hamstrings],
      aliases: ['band glute bridge'],
      keywords: ['floor hip extension', 'glute activation'],
    ),
    _ExerciseSeed(
      'cable_pull_through',
      'Cable Glute Pull-Through',
      MuscleGroup.glutes,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.hamstrings],
      aliases: ['cable pull through'],
      keywords: ['hip hinge', 'hip extension'],
    ),
    _ExerciseSeed(
      'cable_kickback',
      'Cable glute kickback',
      MuscleGroup.glutes,
      ExerciseEquipment.cable,
      aliases: ['cable kickback', 'glute kickback'],
      keywords: ['hip extension', 'glute isolation'],
    ),
    _ExerciseSeed(
      'machine_glute_kickback',
      'Machine Glute Kickback',
      MuscleGroup.glutes,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['glute kickback machine'],
      keywords: ['hip extension', 'glute isolation'],
    ),
    _ExerciseSeed(
      'hip_abduction_machine',
      'Hip Abduction Machine',
      MuscleGroup.glutes,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['seated hip abduction'],
      keywords: ['outer glute', 'glute medius'],
    ),
    _ExerciseSeed(
      'cable_hip_abduction',
      'Cable Hip Abduction',
      MuscleGroup.glutes,
      ExerciseEquipment.cable,
      aliases: ['standing cable abduction'],
      keywords: ['outer glute', 'glute medius'],
    ),
    _ExerciseSeed(
      'banded_hip_abduction',
      'Banded Hip Abduction',
      MuscleGroup.glutes,
      ExerciseEquipment.resistanceBand,
      aliases: ['band abduction'],
      keywords: ['outer glute', 'glute medius'],
    ),
    _ExerciseSeed(
      'frog_pump',
      'Frog Pump',
      MuscleGroup.glutes,
      ExerciseEquipment.bodyweight,
      aliases: ['frog glute bridge'],
      keywords: ['hip extension', 'glute isolation'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'reverse_hyperextension',
      'Reverse Hyperextension',
      MuscleGroup.glutes,
      ExerciseEquipment.machine,
      secondary: [MuscleGroup.hamstrings, MuscleGroup.back],
      aliases: ['reverse hyper'],
      keywords: ['posterior chain', 'hip extension'],
    ),
    _ExerciseSeed(
      'barbell_step_up_glute',
      'High Box Barbell Step-Up',
      MuscleGroup.glutes,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.quadriceps, MuscleGroup.hamstrings],
      aliases: ['high step up'],
      keywords: ['unilateral glutes', 'hip extension'],
    ),
    _ExerciseSeed(
      'cable_hip_adduction',
      'Cable Hip Adduction',
      MuscleGroup.glutes,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.quadriceps],
      aliases: ['standing cable adduction'],
      keywords: ['inner thigh', 'adductors'],
    ),
    _ExerciseSeed(
      'hip_adduction_machine',
      'Hip Adduction Machine',
      MuscleGroup.glutes,
      ExerciseEquipment.selectorisedMachine,
      secondary: [MuscleGroup.quadriceps],
      aliases: ['seated hip adduction'],
      keywords: ['inner thigh', 'adductors'],
    ),

    // Calves and lower leg
    _ExerciseSeed(
      'standing_calf_raise',
      'Standing calf raise',
      MuscleGroup.calves,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['calf raise machine'],
      keywords: ['gastrocnemius', 'lower leg'],
    ),
    _ExerciseSeed(
      'seated_calf_raise',
      'Seated Calf Raise',
      MuscleGroup.calves,
      ExerciseEquipment.plateLoadedMachine,
      aliases: ['seated calf machine'],
      keywords: ['soleus', 'lower leg'],
    ),
    _ExerciseSeed(
      'leg_press_calf_raise',
      'Leg Press Calf Raise',
      MuscleGroup.calves,
      ExerciseEquipment.plateLoadedMachine,
      aliases: ['calf press'],
      keywords: ['gastrocnemius', 'lower leg'],
    ),
    _ExerciseSeed(
      'smith_machine_calf_raise',
      'Smith Machine Calf Raise',
      MuscleGroup.calves,
      ExerciseEquipment.smithMachine,
      aliases: ['smith calf raise'],
      keywords: ['gastrocnemius', 'lower leg'],
    ),
    _ExerciseSeed(
      'single_leg_calf_raise',
      'Single-leg calf raise',
      MuscleGroup.calves,
      ExerciseEquipment.bodyweight,
      aliases: ['one leg calf raise'],
      keywords: ['unilateral calf', 'lower leg'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'donkey_calf_raise',
      'Donkey Calf Raise',
      MuscleGroup.calves,
      ExerciseEquipment.plateLoadedMachine,
      aliases: ['bent over calf raise'],
      keywords: ['gastrocnemius', 'lower leg'],
    ),
    _ExerciseSeed(
      'tibialis_raise',
      'Standing Tibialis Raise',
      MuscleGroup.calves,
      ExerciseEquipment.bodyweight,
      aliases: ['tib raise'],
      keywords: ['shin raise', 'anterior lower leg'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'seated_tibialis_raise',
      'Seated Tibialis Raise',
      MuscleGroup.calves,
      ExerciseEquipment.other,
      aliases: ['weighted tib raise'],
      keywords: ['shin raise', 'anterior lower leg'],
    ),
    _ExerciseSeed(
      'jump_rope_calf_hops',
      'Jump-Rope Calf Hops',
      MuscleGroup.calves,
      ExerciseEquipment.other,
      aliases: ['pogo hops'],
      keywords: ['ankle stiffness', 'lower leg plyometric'],
      trackingType: ExerciseTrackingType.duration,
    ),

    // Core
    _ExerciseSeed(
      'cable_crunch',
      'Cable crunch',
      MuscleGroup.core,
      ExerciseEquipment.cable,
      aliases: ['kneeling cable crunch'],
      keywords: ['abs', 'abdominals', 'spinal flexion'],
    ),
    _ExerciseSeed(
      'machine_crunch',
      'Machine Crunch',
      MuscleGroup.core,
      ExerciseEquipment.selectorisedMachine,
      aliases: ['ab crunch machine'],
      keywords: ['abs', 'abdominals', 'spinal flexion'],
    ),
    _ExerciseSeed(
      'decline_crunch',
      'Decline Crunch',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      aliases: ['decline sit up'],
      keywords: ['abs', 'abdominals'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'sit_up',
      'Sit-Up',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      aliases: ['situp'],
      keywords: ['abs', 'abdominals'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'hanging_leg_raise',
      'Hanging Leg Raise',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.forearms],
      aliases: ['straight leg raise'],
      keywords: ['abs', 'lower abs'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'hanging_knee_raise',
      'Hanging Knee Raise',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.forearms],
      aliases: ['hanging knees'],
      keywords: ['abs', 'lower abs'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'captains_chair_knee_raise',
      "Captain's Chair Knee Raise",
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      aliases: ['roman chair knee raise'],
      keywords: ['abs', 'lower abs'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'reverse_crunch',
      'Reverse Crunch',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      aliases: ['hip lift crunch'],
      keywords: ['abs', 'lower abs'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'ab_wheel_rollout',
      'Ab wheel rollout',
      MuscleGroup.core,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.shoulders],
      aliases: ['ab roller'],
      keywords: ['abs', 'anti extension'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'plank',
      'Plank',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      aliases: ['front plank'],
      keywords: ['abs', 'anti extension', 'isometric'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'weighted_plank',
      'Weighted Plank',
      MuscleGroup.core,
      ExerciseEquipment.other,
      aliases: ['loaded plank'],
      keywords: ['abs', 'anti extension', 'isometric'],
      trackingType: ExerciseTrackingType.weightAndDuration,
      bodyweightRelevant: true,
    ),
    _ExerciseSeed(
      'side_plank',
      'Side Plank',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      aliases: ['lateral plank'],
      keywords: ['obliques', 'abs', 'anti lateral flexion'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'pallof_press',
      'Pallof Press',
      MuscleGroup.core,
      ExerciseEquipment.cable,
      aliases: ['cable anti rotation press'],
      keywords: ['abs', 'anti rotation'],
    ),
    _ExerciseSeed(
      'band_pallof_press',
      'Resistance-Band Pallof Press',
      MuscleGroup.core,
      ExerciseEquipment.resistanceBand,
      aliases: ['band anti rotation press'],
      keywords: ['abs', 'anti rotation'],
    ),
    _ExerciseSeed(
      'cable_wood_chop',
      'Cable Wood Chop',
      MuscleGroup.core,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.shoulders],
      aliases: ['cable chop'],
      keywords: ['obliques', 'abs', 'rotation'],
    ),
    _ExerciseSeed(
      'russian_twist',
      'Russian Twist',
      MuscleGroup.core,
      ExerciseEquipment.medicineBall,
      aliases: ['seated torso twist'],
      keywords: ['obliques', 'abs', 'rotation'],
    ),
    _ExerciseSeed(
      'dead_bug',
      'Dead Bug',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      aliases: ['deadbug'],
      keywords: ['abs', 'anti extension', 'coordination'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'bird_dog',
      'Bird Dog',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.glutes, MuscleGroup.back],
      aliases: ['quadruped reach'],
      keywords: ['abs', 'spinal stability'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'hollow_body_hold',
      'Hollow Body Hold',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      aliases: ['hollow hold'],
      keywords: ['abs', 'gymnastics core', 'isometric'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'mountain_climber',
      'Mountain Climber',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.shoulders, MuscleGroup.cardio],
      aliases: ['mountain climbers'],
      keywords: ['abs', 'conditioning'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'bicycle_crunch',
      'Bicycle Crunch',
      MuscleGroup.core,
      ExerciseEquipment.bodyweight,
      aliases: ['bicycle abs'],
      keywords: ['obliques', 'abs', 'abdominals'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'medicine_ball_sit_up',
      'Medicine-Ball Sit-Up',
      MuscleGroup.core,
      ExerciseEquipment.medicineBall,
      aliases: ['weighted sit up'],
      keywords: ['abs', 'abdominals'],
    ),

    // Full body and power
    _ExerciseSeed(
      'conventional_deadlift',
      'Conventional deadlift',
      MuscleGroup.fullBody,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.back, MuscleGroup.glutes, MuscleGroup.hamstrings],
      aliases: ['deadlift'],
      keywords: ['posterior chain', 'powerlifting'],
    ),
    _ExerciseSeed(
      'sumo_deadlift',
      'Sumo Deadlift',
      MuscleGroup.fullBody,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.back],
      aliases: ['wide stance deadlift'],
      keywords: ['posterior chain', 'powerlifting'],
    ),
    _ExerciseSeed(
      'trap_bar_deadlift',
      'Trap-Bar Deadlift',
      MuscleGroup.fullBody,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.quadriceps, MuscleGroup.glutes, MuscleGroup.back],
      aliases: ['hex bar deadlift'],
      keywords: ['posterior chain', 'leg strength'],
    ),
    _ExerciseSeed(
      'clean',
      'Barbell Clean',
      MuscleGroup.fullBody,
      ExerciseEquipment.barbell,
      aliases: ['olympic clean'],
      keywords: ['power', 'weightlifting'],
    ),
    _ExerciseSeed(
      'power_clean',
      'Power Clean',
      MuscleGroup.fullBody,
      ExerciseEquipment.barbell,
      aliases: ['barbell power clean'],
      keywords: ['power', 'weightlifting'],
    ),
    _ExerciseSeed(
      'hang_clean',
      'Hang Clean',
      MuscleGroup.fullBody,
      ExerciseEquipment.barbell,
      aliases: ['barbell hang clean'],
      keywords: ['power', 'weightlifting'],
    ),
    _ExerciseSeed(
      'clean_and_press',
      'Clean and Press',
      MuscleGroup.fullBody,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.shoulders, MuscleGroup.triceps],
      aliases: ['clean press'],
      keywords: ['power', 'weightlifting', 'overhead'],
    ),
    _ExerciseSeed(
      'barbell_snatch',
      'Barbell Snatch',
      MuscleGroup.fullBody,
      ExerciseEquipment.barbell,
      aliases: ['snatch'],
      keywords: ['power', 'weightlifting', 'overhead'],
    ),
    _ExerciseSeed(
      'dumbbell_thruster',
      'Dumbbell thruster',
      MuscleGroup.fullBody,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.quadriceps, MuscleGroup.shoulders],
      aliases: ['db thruster'],
      keywords: ['squat press', 'conditioning'],
    ),
    _ExerciseSeed(
      'barbell_thruster',
      'Barbell Thruster',
      MuscleGroup.fullBody,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.quadriceps, MuscleGroup.shoulders],
      aliases: ['front squat press'],
      keywords: ['squat press', 'conditioning'],
    ),
    _ExerciseSeed(
      'kettlebell_swing',
      'Kettlebell swing',
      MuscleGroup.fullBody,
      ExerciseEquipment.kettlebell,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.core],
      aliases: ['kb swing'],
      keywords: ['hip hinge', 'power', 'conditioning'],
    ),
    _ExerciseSeed(
      'turkish_get_up',
      'Turkish Get-Up',
      MuscleGroup.fullBody,
      ExerciseEquipment.kettlebell,
      secondary: [MuscleGroup.shoulders, MuscleGroup.core],
      aliases: ['tgu'],
      keywords: ['getup', 'stability', 'mobility'],
    ),
    _ExerciseSeed(
      'battle_rope_slams',
      'Battle Rope Slams',
      MuscleGroup.fullBody,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.shoulders, MuscleGroup.core, MuscleGroup.cardio],
      aliases: ['battle ropes'],
      keywords: ['conditioning', 'rope waves'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'sled_push',
      'Sled Push',
      MuscleGroup.fullBody,
      ExerciseEquipment.other,
      secondary: [
        MuscleGroup.quadriceps,
        MuscleGroup.glutes,
        MuscleGroup.cardio,
      ],
      aliases: ['prowler push'],
      keywords: ['conditioning', 'loaded carry'],
      trackingType: ExerciseTrackingType.weightAndDistance,
    ),
    _ExerciseSeed(
      'sled_pull',
      'Sled Pull',
      MuscleGroup.fullBody,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.back, MuscleGroup.glutes, MuscleGroup.cardio],
      aliases: ['sled drag'],
      keywords: ['conditioning', 'loaded carry'],
      trackingType: ExerciseTrackingType.weightAndDistance,
    ),
    _ExerciseSeed(
      'farmer_carry',
      'Farmer carry',
      MuscleGroup.fullBody,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.forearms, MuscleGroup.core],
      aliases: ['farmers walk', 'farmer carry'],
      keywords: ['loaded carry', 'grip'],
      trackingType: ExerciseTrackingType.weightAndDistance,
    ),
    _ExerciseSeed(
      'sandbag_carry',
      'Sandbag Carry',
      MuscleGroup.fullBody,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.core, MuscleGroup.forearms],
      aliases: ['bear hug carry'],
      keywords: ['loaded carry', 'conditioning'],
      trackingType: ExerciseTrackingType.weightAndDistance,
    ),
    _ExerciseSeed(
      'burpee',
      'Burpee',
      MuscleGroup.fullBody,
      ExerciseEquipment.bodyweight,
      secondary: [
        MuscleGroup.cardio,
        MuscleGroup.chest,
        MuscleGroup.quadriceps,
      ],
      aliases: ['burpees'],
      keywords: ['conditioning', 'bodyweight power'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'medicine_ball_slam',
      'Medicine-Ball Slam',
      MuscleGroup.fullBody,
      ExerciseEquipment.medicineBall,
      secondary: [MuscleGroup.core, MuscleGroup.shoulders],
      aliases: ['med ball slam'],
      keywords: ['power', 'conditioning'],
      trackingType: ExerciseTrackingType.repetitions,
    ),

    // Cardio
    _ExerciseSeed(
      'treadmill_run',
      'Treadmill run',
      MuscleGroup.cardio,
      ExerciseEquipment.cardioEquipment,
      aliases: ['treadmill', 'indoor run'],
      keywords: ['running', 'run', 'jog'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'incline_treadmill_walk',
      'Incline Treadmill Walking',
      MuscleGroup.cardio,
      ExerciseEquipment.cardioEquipment,
      secondary: [MuscleGroup.glutes, MuscleGroup.calves],
      aliases: ['incline treadmill'],
      keywords: ['walking', 'hiking', 'cardio'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'outdoor_walking',
      'Outdoor Walking',
      MuscleGroup.cardio,
      ExerciseEquipment.other,
      aliases: ['walk', 'outdoor walk'],
      keywords: ['steps', 'hiking', 'cardio'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'outdoor_running',
      'Outdoor Running',
      MuscleGroup.cardio,
      ExerciseEquipment.other,
      aliases: ['run', 'road running'],
      keywords: ['jogging', 'cardio'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'stationary_bike',
      'Stationary bike',
      MuscleGroup.cardio,
      ExerciseEquipment.cardioEquipment,
      secondary: [MuscleGroup.quadriceps],
      aliases: ['exercise bike', 'indoor bike'],
      keywords: ['cycling', 'cycle', 'bicycle'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'spin_bike',
      'Spin Bike',
      MuscleGroup.cardio,
      ExerciseEquipment.cardioEquipment,
      secondary: [MuscleGroup.quadriceps, MuscleGroup.glutes],
      aliases: ['spinning bike'],
      keywords: ['cycling', 'cycle', 'bicycle'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'recumbent_bike',
      'Recumbent Bike',
      MuscleGroup.cardio,
      ExerciseEquipment.cardioEquipment,
      secondary: [MuscleGroup.quadriceps],
      aliases: ['seated exercise bike'],
      keywords: ['cycling', 'cycle', 'bicycle'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'outdoor_cycling',
      'Outdoor Cycling',
      MuscleGroup.cardio,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.quadriceps, MuscleGroup.glutes],
      aliases: ['road bike', 'bike ride'],
      keywords: ['cycling', 'cycle', 'bicycle'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'rowing_ergometer',
      'Rowing ergometer',
      MuscleGroup.cardio,
      ExerciseEquipment.cardioEquipment,
      secondary: [MuscleGroup.back, MuscleGroup.quadriceps],
      aliases: ['rower', 'rowing ergometer'],
      keywords: ['erg', 'indoor rowing'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'elliptical',
      'Elliptical Trainer',
      MuscleGroup.cardio,
      ExerciseEquipment.cardioEquipment,
      aliases: ['cross trainer'],
      keywords: ['low impact cardio'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'stair_climber',
      'Stair Climber',
      MuscleGroup.cardio,
      ExerciseEquipment.cardioEquipment,
      secondary: [MuscleGroup.glutes, MuscleGroup.quadriceps],
      aliases: ['stairmaster', 'stairs machine'],
      keywords: ['stepper', 'climbing'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'ski_erg',
      'Ski Erg',
      MuscleGroup.cardio,
      ExerciseEquipment.cardioEquipment,
      secondary: [MuscleGroup.back, MuscleGroup.triceps, MuscleGroup.core],
      aliases: ['ski ergometer'],
      keywords: ['skiing', 'upper body cardio'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'assault_bike',
      'Air Bike',
      MuscleGroup.cardio,
      ExerciseEquipment.cardioEquipment,
      secondary: [MuscleGroup.fullBody],
      aliases: ['assault bike', 'fan bike'],
      keywords: ['cycling', 'bike', 'conditioning'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'jump_rope',
      'Jump Rope',
      MuscleGroup.cardio,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.calves],
      aliases: ['skipping rope', 'skipping'],
      keywords: ['conditioning', 'jumps'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'swimming',
      'Swimming',
      MuscleGroup.cardio,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.fullBody],
      aliases: ['swim', 'pool laps'],
      keywords: ['aquatic cardio'],
      trackingType: ExerciseTrackingType.distanceAndDuration,
    ),
    _ExerciseSeed(
      'stepmill',
      'Stepmill',
      MuscleGroup.cardio,
      ExerciseEquipment.cardioEquipment,
      secondary: [MuscleGroup.glutes, MuscleGroup.quadriceps],
      aliases: ['moving stairs'],
      keywords: ['stair cardio', 'climbing'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'battle_rope_intervals',
      'Battle Rope Intervals',
      MuscleGroup.cardio,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.shoulders, MuscleGroup.core],
      aliases: ['rope waves'],
      keywords: ['conditioning', 'hiit'],
      trackingType: ExerciseTrackingType.duration,
    ),

    // Mobility
    _ExerciseSeed(
      'worlds_greatest_stretch',
      "World's Greatest Stretch",
      MuscleGroup.mobility,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.back],
      aliases: ['lunge rotation stretch'],
      keywords: ['hip mobility', 'thoracic mobility', 'warm up'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'ninety_ninety_hip_switch',
      '90/90 Hip Switch',
      MuscleGroup.mobility,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.glutes],
      aliases: ['90 90 hips'],
      keywords: ['hip rotation', 'hip mobility'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'couch_stretch',
      'Couch Stretch',
      MuscleGroup.mobility,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.quadriceps, MuscleGroup.glutes],
      aliases: ['kneeling hip flexor stretch'],
      keywords: ['hip mobility', 'quad stretch'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'kneeling_adductor_rock_back',
      'Kneeling Adductor Rock-Back',
      MuscleGroup.mobility,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.glutes],
      aliases: ['adductor rockback'],
      keywords: ['groin mobility', 'hip mobility'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'ankle_dorsiflexion_mobilisation',
      'Ankle Dorsiflexion Mobilisation',
      MuscleGroup.mobility,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.calves],
      aliases: ['knee to wall'],
      keywords: ['ankle mobility', 'calf stretch'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'banded_ankle_mobilisation',
      'Banded Ankle Mobilisation',
      MuscleGroup.mobility,
      ExerciseEquipment.resistanceBand,
      secondary: [MuscleGroup.calves],
      aliases: ['banded ankle mob'],
      keywords: ['ankle mobility', 'dorsiflexion'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'thoracic_open_book',
      'Thoracic Open Book',
      MuscleGroup.mobility,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.back, MuscleGroup.shoulders],
      aliases: ['open book stretch'],
      keywords: ['thoracic rotation', 'upper back mobility'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'foam_roller_thoracic_extension',
      'Foam-Roller Thoracic Extension',
      MuscleGroup.mobility,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.back],
      aliases: ['thoracic foam roll'],
      keywords: ['upper back mobility', 't spine extension'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'wall_shoulder_flexion',
      'Wall Shoulder Flexion',
      MuscleGroup.mobility,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.shoulders, MuscleGroup.back],
      aliases: ['wall overhead reach'],
      keywords: ['shoulder mobility', 'lat stretch'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'dowel_shoulder_dislocate',
      'Dowel Shoulder Pass-Through',
      MuscleGroup.mobility,
      ExerciseEquipment.other,
      secondary: [MuscleGroup.shoulders, MuscleGroup.chest],
      aliases: ['shoulder dislocate'],
      keywords: ['shoulder mobility', 'pec stretch'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'deep_squat_hold',
      'Deep Squat Hold',
      MuscleGroup.mobility,
      ExerciseEquipment.bodyweight,
      secondary: [
        MuscleGroup.quadriceps,
        MuscleGroup.glutes,
        MuscleGroup.calves,
      ],
      aliases: ['squat pry'],
      keywords: ['hip mobility', 'ankle mobility'],
      trackingType: ExerciseTrackingType.duration,
    ),
    _ExerciseSeed(
      'cat_cow',
      'Cat-Cow',
      MuscleGroup.mobility,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.back, MuscleGroup.core],
      aliases: ['cat camel'],
      keywords: ['spine mobility', 'warm up'],
      trackingType: ExerciseTrackingType.repetitions,
    ),

    // Rehabilitation
    _ExerciseSeed(
      'band_external_rotation',
      'Band External Rotation',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.resistanceBand,
      secondary: [MuscleGroup.shoulders],
      aliases: ['rotator cuff external rotation'],
      keywords: ['shoulder rehab', 'infraspinatus'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'cable_external_rotation',
      'Cable External Rotation',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.cable,
      secondary: [MuscleGroup.shoulders],
      aliases: ['rotator cuff cable rotation'],
      keywords: ['shoulder rehab', 'infraspinatus'],
    ),
    _ExerciseSeed(
      'band_internal_rotation',
      'Band Internal Rotation',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.resistanceBand,
      secondary: [MuscleGroup.shoulders],
      aliases: ['rotator cuff internal rotation'],
      keywords: ['shoulder rehab', 'subscapularis'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'wall_slide',
      'Wall Slide',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.shoulders, MuscleGroup.back],
      aliases: ['wall angel'],
      keywords: ['shoulder rehab', 'scapular control'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'scapular_push_up',
      'Scapular Push-Up',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.shoulders, MuscleGroup.chest],
      aliases: ['push up plus'],
      keywords: ['serratus', 'shoulder rehab'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'banded_terminal_knee_extension',
      'Banded Terminal Knee Extension',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.resistanceBand,
      secondary: [MuscleGroup.quadriceps],
      aliases: ['tke', 'terminal knee extension'],
      keywords: ['knee rehab', 'quad activation'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'straight_leg_raise_rehab',
      'Supine Straight-Leg Raise',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.quadriceps, MuscleGroup.core],
      aliases: ['straight leg raise rehab'],
      keywords: ['knee rehab', 'quad activation'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'side_lying_hip_abduction',
      'Side-Lying Hip Abduction',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.glutes],
      aliases: ['side leg raise'],
      keywords: ['hip rehab', 'glute medius'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'clamshell',
      'Clamshell',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.resistanceBand,
      secondary: [MuscleGroup.glutes],
      aliases: ['band clamshell'],
      keywords: ['hip rehab', 'glute medius'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'eccentric_heel_drop',
      'Eccentric Heel Drop',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.calves],
      aliases: ['alfredson heel drop'],
      keywords: ['achilles rehab', 'calf eccentric'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'banded_ankle_inversion',
      'Banded Ankle Inversion',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.resistanceBand,
      secondary: [MuscleGroup.calves],
      aliases: ['ankle inward band'],
      keywords: ['ankle rehab', 'tibialis posterior'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'banded_ankle_eversion',
      'Banded Ankle Eversion',
      MuscleGroup.rehabilitation,
      ExerciseEquipment.resistanceBand,
      secondary: [MuscleGroup.calves],
      aliases: ['ankle outward band'],
      keywords: ['ankle rehab', 'peroneals'],
      trackingType: ExerciseTrackingType.repetitions,
    ),

    // Other useful movements
    _ExerciseSeed(
      'neck_flexion',
      'Neck Flexion',
      MuscleGroup.other,
      ExerciseEquipment.other,
      aliases: ['neck curl'],
      keywords: ['neck training', 'cervical flexion'],
    ),
    _ExerciseSeed(
      'neck_extension',
      'Neck Extension',
      MuscleGroup.other,
      ExerciseEquipment.other,
      aliases: ['neck raise'],
      keywords: ['neck training', 'cervical extension'],
    ),
    _ExerciseSeed(
      'barbell_shrug',
      'Barbell Shrug',
      MuscleGroup.other,
      ExerciseEquipment.barbell,
      secondary: [MuscleGroup.back, MuscleGroup.shoulders],
      aliases: ['shrug'],
      keywords: ['upper traps', 'trapezius'],
    ),
    _ExerciseSeed(
      'dumbbell_shrug',
      'Dumbbell Shrug',
      MuscleGroup.other,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.back, MuscleGroup.shoulders],
      aliases: ['db shrug'],
      keywords: ['upper traps', 'trapezius'],
    ),
    _ExerciseSeed(
      'machine_shrug',
      'Plate-Loaded Machine Shrug',
      MuscleGroup.other,
      ExerciseEquipment.plateLoadedMachine,
      secondary: [MuscleGroup.back, MuscleGroup.shoulders],
      aliases: ['machine shrug'],
      keywords: ['upper traps', 'trapezius'],
    ),
    _ExerciseSeed(
      'standing_side_bend',
      'Dumbbell Side Bend',
      MuscleGroup.other,
      ExerciseEquipment.dumbbell,
      secondary: [MuscleGroup.core],
      aliases: ['standing side bend'],
      keywords: ['obliques', 'lateral flexion'],
    ),
    _ExerciseSeed(
      'breathing_squat',
      'Bodyweight Breathing Squat',
      MuscleGroup.other,
      ExerciseEquipment.bodyweight,
      secondary: [MuscleGroup.quadriceps, MuscleGroup.glutes],
      aliases: ['air squat breathing'],
      keywords: ['movement practice', 'recovery'],
      trackingType: ExerciseTrackingType.repetitions,
    ),
    _ExerciseSeed(
      'box_breathing',
      'Box Breathing',
      MuscleGroup.other,
      ExerciseEquipment.other,
      aliases: ['four square breathing'],
      keywords: ['breathwork', 'recovery'],
      trackingType: ExerciseTrackingType.duration,
    ),
  ];
}

class _ExerciseSeed {
  const _ExerciseSeed(
    this.key,
    this.name,
    this.primaryMuscleGroup,
    this.equipment, {
    this.secondary = const [],
    this.aliases = const [],
    this.keywords = const [],
    this.trackingType = ExerciseTrackingType.weightAndRepetitions,
    this.bodyweightRelevant,
  });

  final String key;
  final String name;
  final MuscleGroup primaryMuscleGroup;
  final ExerciseEquipment equipment;
  final List<MuscleGroup> secondary;
  final List<String> aliases;
  final List<String> keywords;
  final ExerciseTrackingType trackingType;
  final bool? bodyweightRelevant;

  ExerciseSelection build() {
    final aliasValues = <String>{key.replaceAll('_', ' '), ...aliases};
    final keywordValues = <String>{
      primaryMuscleGroup.label,
      equipment.label,
      ...keywords,
    };
    final weightRelevant = switch (trackingType) {
      ExerciseTrackingType.weightAndRepetitions ||
      ExerciseTrackingType.weightAndDistance ||
      ExerciseTrackingType.weightAndDuration => true,
      _ => false,
    };
    final repetitionsRelevant = switch (trackingType) {
      ExerciseTrackingType.weightAndRepetitions ||
      ExerciseTrackingType.repetitions => true,
      _ => false,
    };
    final distanceRelevant = switch (trackingType) {
      ExerciseTrackingType.distanceAndDuration ||
      ExerciseTrackingType.weightAndDistance => true,
      _ => false,
    };
    final durationRelevant = switch (trackingType) {
      ExerciseTrackingType.duration ||
      ExerciseTrackingType.distanceAndDuration ||
      ExerciseTrackingType.weightAndDuration => true,
      _ => false,
    };

    return ExerciseSelection.system(
      key: key,
      name: name,
      primaryMuscleGroup: primaryMuscleGroup,
      secondaryMuscleGroups: List.unmodifiable(secondary),
      equipment: equipment,
      aliases: List.unmodifiable(aliasValues),
      keywords: List.unmodifiable(keywordValues),
      trackingType: trackingType,
      weightRelevant: weightRelevant,
      repetitionsRelevant: repetitionsRelevant,
      distanceRelevant: distanceRelevant,
      durationRelevant: durationRelevant,
      bodyweightRelevant:
          bodyweightRelevant ?? equipment == ExerciseEquipment.bodyweight,
    );
  }
}
